### ISSUE TITLE
prometheusInstrumentApp is never actually used

### ISSUE THREAD

**Issue by ocharles** [fimad/prometheus-haskell#31] opened 2018-01-24 13:42 UTC
Weird one, but `prometheusInstrumentApp` is never actually used anywhere... This means that with PR #29, even if you set `prometheusInstrumentApp` to `False`, you'll still double instrument everything.

**Comment by fimad** [comment] 2018-01-25 06:12
I think this is a dupe of #26

**Closed** 2018-07-16 07:37 UTC
